In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from neural_exploration import *
sns.set()

In [2]:
T = 2000
n_arms = 12 # a -> 숫자를 키워볼 것
n_features = 20 # d -> 숫자를 키워볼 것
n_assortment = 4
noise_std = 0.1

n_samples = 1 # number of samples for each round and arm, only for TS

n_sim = 2 # number of simulations

def F(x): # round_reward_function
    if len(np.shape(x)) == 1: # if x is a vector
        return np.sum(x)
    else: # if x is a matrix
        return np.sum(x, axis=1)                

In [3]:
reg_factor = 1.0 # lambda
delta = 0.1 # delta
exploration_variance = 1.0 # nu, only for TS
confidence_scaling_factor = 1.0 # gamma, only for UCB

In [4]:
p = 0.2 # dropout probability
hidden_size = 64 # m
epochs = 100 # 
train_every = 10
confidence_scaling_factor = 1.0
use_cuda = False

In [5]:
### mean reward function
a = np.random.randn(n_features)
a /= np.linalg.norm(a, ord=2)
h = lambda x: 100*np.dot(a, x)

In [6]:
bandit = ContextualBandit(T, n_arms, n_features, h, noise_std=noise_std, \
                          n_assortment=n_assortment, n_samples=n_samples, round_reward_function=F)

regrets = np.empty((n_sim, T))

bandit.reset_rewards()
model = NeuralUCB(bandit,
                  hidden_size=hidden_size,
                  reg_factor=reg_factor,
                  delta=delta,
                  confidence_scaling_factor=confidence_scaling_factor,
                  # exploration_variance=exploration_variance,
                  training_window=100,
                  p=p,
                  learning_rate=0.01,
                  epochs=epochs,
                  train_every=train_every,
                  use_cuda=use_cuda
                 )

lin_model = LinUCB(bandit,
                   reg_factor=reg_factor,
                   delta=delta,
                   confidence_scaling_factor=confidence_scaling_factor
                  )

In [8]:
inital_parameters = model.model.parameters()

<generator object Module.parameters at 0x7f55cdaa3bd0>

In [44]:
model.model.train()

Model(
  (layers): ModuleList(
    (0): Linear(in_features=20, out_features=64, bias=False)
    (1): Linear(in_features=64, out_features=1, bias=False)
  )
  (dropout): Dropout(p=0.2, inplace=False)
  (activation): ReLU()
)

In [60]:
aa = torch.empty(1)

In [69]:
aa - aa

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [68]:
aa = torch.empty(1)
for p in model.model.parameters():
    aa = torch.cat((aa, p.data.flatten()))
aa = aa[1:]

In [66]:
aa.size()

torch.Size([1344])

In [46]:
for p in model.model.get_initial_parameters():
    print(np.linalg.norm(p.data.flatten()))

4.6717014
0.5899825


In [8]:
np.random.randn()

1.302046392073708

In [7]:
model.approximator_dim

1344

In [15]:
input_size = 20
hidden_size = 64
n_layers = 2

size  = [input_size] + [hidden_size,] * (n_layers-1) + [1]
layers = [nn.Linear(size[i], size[i+1], bias = False) for i in range(n_layers)]

In [16]:
layers

[Linear(in_features=20, out_features=64, bias=False),
 Linear(in_features=64, out_features=1, bias=False)]

1409

In [11]:
lin_model.approximator_dim

20

In [11]:
np.max(bb, axis=-1)

array([ 9, 17, 10,  7, 15])

In [5]:
aa = np.array([[9,17,10,7,15]])
np.shape(aa)
bb = np.reshape(aa, (5,1))
np.shape(bb)
bbb

array([[ 9],
       [17],
       [10],
       [ 7],
       [15]])

In [2]:
## --
aa = np.array([[9,17,10,7,15], [20,22,21,27,26], [1,2,3,4,5]])

aa[1, np.array([0,2])]

array([20, 21])

In [ ]:
## --
a = np.array([9,17,10,7,15])
ind = np.argpartition(a, -3)[-3:]
s_ind = ind[np.argsort(a[ind])][::-1]
b = a[s_ind]

print(s_ind)
print(b)

In [ ]:
## --
def inv_sherman_morrison_iter(a, A_inv):
    temp = A_inv
    for u in a:
        print(np.shape(u))
        print(np.shape(temp))
        Au = np.dot(temp, u)
        temp = temp - np.outer(Au, Au)/(1+np.dot(u.T, Au))
    return temp

In [ ]:
c = np.array( [np.array([1,0]) , np.array([0,1]), np.array([1,0]) , np.array([0,1])] )
A_inv = np.array( [[np.array([1,0]) , np.array([0,1])]] )
A_inv = np.squeeze(A_inv, axis=0)

inv_sherman_morrison_iter(c, A_inv)


In [ ]:
## --
a = np.array([[9,17,10,7,15], [20,22,21,27,26]])
ind = np.argpartition(a, -3, axis=1)[:,-3:]
s_ind = np.array([list(ind[i][np.argsort(a[i][ind[i]])][::-1]) for i in range(0, np.shape(a)[0])])
b = np.array([a[i][s_ind[i]] for i in range(0,np.shape(a)[0])])

In [ ]:
## --
print(s_ind)
print(b)

In [ ]:
## --
bandit = ContextualBandit(T, n_arms, n_features, h, noise_std=noise_std, n_assortment=n_assortment, round_reward_function=F)

In [ ]:
## --
print('super arm:', bandit.best_super_arm)
print('scores:', bandit.best_rewards)
print('round reward:', bandit.best_round_reward)

In [3]:
import numpy as np 

aa = np.array([[9,17,10,7,15]])
bb = np.array([[12,17,14,7,15]])

np.linalg.norm(aa-bb)

5.0