In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#from neural_exploration import *
sns.set()

In [5]:
aa = np.array([[9,17,10,7,15]])
np.shape(aa)
bb = np.reshape(aa, (5,1))
np.shape(bb)
bbb

array([[ 9],
       [17],
       [10],
       [ 7],
       [15]])

In [11]:
np.max(bb, axis=-1)

array([ 9, 17, 10,  7, 15])

In [2]:
## --
aa = np.array([[9,17,10,7,15], [20,22,21,27,26], [1,2,3,4,5]])

aa[1, np.array([0,2])]

array([20, 21])

In [ ]:
## --
a = np.array([9,17,10,7,15])
ind = np.argpartition(a, -3)[-3:]
s_ind = ind[np.argsort(a[ind])][::-1]
b = a[s_ind]

print(s_ind)
print(b)

In [ ]:
## --
def inv_sherman_morrison_iter(a, A_inv):
    temp = A_inv
    for u in a:
        print(np.shape(u))
        print(np.shape(temp))
        Au = np.dot(temp, u)
        temp = temp - np.outer(Au, Au)/(1+np.dot(u.T, Au))
    return temp

In [ ]:
c = np.array( [np.array([1,0]) , np.array([0,1]), np.array([1,0]) , np.array([0,1])] )
A_inv = np.array( [[np.array([1,0]) , np.array([0,1])]] )
A_inv = np.squeeze(A_inv, axis=0)

inv_sherman_morrison_iter(c, A_inv)


In [ ]:
## --
a = np.array([[9,17,10,7,15], [20,22,21,27,26]])
ind = np.argpartition(a, -3, axis=1)[:,-3:]
s_ind = np.array([list(ind[i][np.argsort(a[i][ind[i]])][::-1]) for i in range(0, np.shape(a)[0])])
b = np.array([a[i][s_ind[i]] for i in range(0,np.shape(a)[0])])

In [ ]:
## --
print(s_ind)
print(b)

In [ ]:
## --
bandit = ContextualBandit(T, n_arms, n_features, h, noise_std=noise_std, n_assortment=n_assortment, round_reward_function=F)

In [ ]:
## --
print('super arm:', bandit.best_super_arm)
print('scores:', bandit.best_rewards)
print('round reward:', bandit.best_round_reward)